name: CI - Test Status

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el código del repositorio
      - name: Check out repository code
        uses: actions/checkout@v3

      # Configurar .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # Compilar el proyecto
      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      # Crear el directorio para los resultados de los tests
      - name: Create Test Results directory
        run: mkdir -p ${{ github.workspace }}/TestResults

      # Ejecutar los tests y generar el reporte en formato HTML
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=${{ github.workspace }}/TestResults/test-results.trx" --logger "html;LogFileName=${{ github.workspace }}/TestResults/test-results.html"

      # Subir el artefacto de los resultados del test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: ${{ github.workspace }}/TestResults/test-results.html
          retention-days: 2

      # Hacer commit del reporte al branch gh-pages
      - name: Push report to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B gh-pages
          mkdir -p html
          mv ${{ github.workspace }}/TestResults/test-results.html html/
          git add html
          git commit -m "Update test results report"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
