name: CI - Test Status

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el código del repositorio
      - name: Check out repository code
        uses: actions/checkout@v3

      # Configurar .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # Compilar el proyecto
      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Create Test Results directory
        run: mkdir -p ${{ github.workspace }}/TestResults

      # Ejecutar los tests y generar el reporte en formato HTML
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=${{ github.workspace }}/TestResults/test-results.trx" --logger "html;LogFileName=${{ github.workspace }}/TestResults/test-results.html"

      # Subir el artefacto de los resultados del test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: ${{ github.workspace }}/TestResults/test-results.html
          retention-days: 2
