name: CI - Test Status

on:
  push:
    branches:
      - master  # Cambia a la rama que uses
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el código del repositorio
      - name: Check out repository code
        uses: actions/checkout@v3

      # Configurar .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # O la versión que estés usando

      # Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # Compilar el proyecto
      - name: Build the solution
        run: dotnet build --configuration Release

      # Crear la carpeta de resultados
      - name: Create TestResults directory
        run: mkdir -p TestResults

      # Ejecutar los tests
      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=TestResults/test-results.trx" --verbosity normal

      # Comprobar si se generó el archivo de resultados
      - name: Check if test results file exists
        run: |
          if [ -f ./TestResults/test-results.trx ]; then
            echo "Test results file found."
          else
            echo "Test results file not found."
            exit 1
          fi
