name: CI - Test Status

# Este flujo de trabajo se ejecutará en cada push a la rama 'main'
on:
  push:
    branches:
      - master  # También puedes cambiarlo a otra rama, como 'develop'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Elige el sistema operativo, puede ser ubuntu-latest o windows-latest

    steps:
      # Clonar el código del repositorio
      - name: Check out repository code
        uses: actions/checkout@v3

      # Configurar .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # O la versión que estés usando (por ejemplo, '6.x')

      # Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      - name: Create Test Results directory
        run: mkdir -p TestResults

      # Compilar el proyecto
      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      # Ejecutar los tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=TestResults/test-results.trx"

      # Subir el artefacto de los resultados del test
      - name: Upload test results
        if: always() # Esto se asegura de que se ejecuta aunque las pruebas fallen
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: TestResults/test-results.trx
          retention-days: 2
