name: CI - Test Status

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el código del repositorio
      - name: Check out repository code
        uses: actions/checkout@v3

      # Configurar .NET SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      # Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore

      # Compilar el proyecto
      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      # Ejecutar los tests y generar el reporte en una carpeta específica
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=TestResults/test-results.trx"

      # Verificar si el archivo de resultados se generó
      - name: List test results directory
        run: ls -la TestResults

      # Subir el artefacto de los resultados del test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: TestResults/test-results.trx
          retention-days: 2
