name: CI - Test Status

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Create TestResults directory
        run: mkdir -p ./TestResults

      - name: Run tests
        run: dotnet test --no-restore --verbosity detailed --logger "trx;LogFileName=TestResults/test-results.trx"

      - name: Check for test results
        run: |
          if [ -f ./TestResults/test-results.trx ]; then
            echo "Test results file found."
          else
            echo "Test results file not found."
            exit 1
          fi

      - name: Generate HTML report
        run: |
          mkdir -p ./TestResults/Report
          dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.3.11
          reportgenerator -reports:./TestResults/test-results.trx -targetdir:./TestResults/Report -reporttypes:Html
